url=jdbc:mysql://localhost:3307/phoneshop_DB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=phoneshop_DB
password=Rith@@11
driver=com.mysql.cj.jdbc.Driver
outputChangeLogFile=src/main/resources/liquibase-outputChangeLog.yml